# Generated by Django 2.1.7 on 2020-02-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('booked_on', models.DateTimeField(null=True)),
                ('is_aisle', models.BooleanField(default=False)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movie_booking.Row')),
            ],
        ),
        migrations.AddField(
            model_name='row',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='movie_booking.Screen'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('row', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='row',
            unique_together={('code', 'screen')},
        ),
    ]
