version: '3'
services:
  db:
    image: mysql:5.7.29
    expose: ["3306"]
    ports:
    - "3310:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webapp_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password 
    volumes:
    - ./data/mysql/data:/var/lib/mysql
    - ./data/mysql/logs:/var/log/mysql/

  webapp:
    build: .
    container_name: webapp_container
    environment:
      DB_HOST: "database"
      DB_PORT: "3306"
      DATABASE: "webapp_db"
      DB_USER: "mysql"
      DB_PASSWORD: "password"
    command: ["./home/app/webapp/scripts/wait-for-mysql.sh", "database", "nginx"]
    ports:
    - "8000:80"
    volumes:
    - .:/code
    - ./data/nginx/logs:/var/log/nginx/
    links:
    - "db:database"
    depends_on:
    - "db"
